version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile_node
    depends_on :
      - redis
    ports:
      - "8000:8000"
    networks:
      - your_network_name

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - your_network_name
  
    
networks:
  your_network_name:

