version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile_node
      args:
        - DATABASE_URL=${DATABASE_URL}  # build-time argument 추가
    depends_on :
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # run-time 환경 변수 추가
    networks:
      - your_network_name

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - your_network_name
  
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "443:443"
    restart : always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - /home/api/api_back/key:/etc/nginx/ssl
    
networks:
  your_network_name:

