FROM node:current-slim

WORKDIR /app

COPY . .

# 환경 변수 설정
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

# package.json에 있는 것들을 설치
RUN apt-get update -y && apt-get install -y openssl
RUN npm install
RUN npx prisma generate
#RUN npx prisma migrate deploy
#8001포트로
EXPOSE 8000

CMD ["sh", "-c", "set TZ=Asia/Seoul && npx prisma migrate deploy && npm run dev"]
