version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile_node
    depends_on :
      - redis
    ports:
      - "8000:8000"
    networks:
      - your_network_name

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - your_network_name
  
  nginxproxy:
    image: nginx:1.18.0
    ports:
      - "80:80"
    restart : always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/site-enable/default:/etc/nginx/site-enable/default"
  nginx: 
    depends_on:
      - nginxproxy
    image: nginx:1.18.0
    restart : always
    
networks:
  your_network_name:

